---
layout: post
title: You might want to avoid using exceptions when things go wrong in your code
date: 2014-12-30 06:25:26.000000000 -07:00
categories: []
tags: []
status: publish
type: post
published: true
meta:
  _edit_last: '1'
  _wp_rp_image: empty
  _wp_rp_related_posts_query_result_cache_expiration: '1443357171'
  _wp_rp_related_posts_query_result_cache_6: a:12:{i:0;O:8:"stdClass":2:{s:7:"post_id";s:3:"222";s:5:"score";s:17:"16.19588727555622";}i:1;O:8:"stdClass":2:{s:7:"post_id";s:4:"1020";s:5:"score";s:17:"14.86022852987661";}i:2;O:8:"stdClass":2:{s:7:"post_id";s:3:"246";s:5:"score";s:17:"14.84108962799525";}i:3;O:8:"stdClass":2:{s:7:"post_id";s:3:"230";s:5:"score";s:18:"13.165632809064466";}i:4;O:8:"stdClass":2:{s:7:"post_id";s:3:"244";s:5:"score";s:17:"12.98955067663974";}i:5;O:8:"stdClass":2:{s:7:"post_id";s:3:"970";s:5:"score";s:18:"12.049543418148268";}i:6;O:8:"stdClass":2:{s:7:"post_id";s:3:"940";s:5:"score";s:18:"11.741242058456017";}i:7;O:8:"stdClass":2:{s:7:"post_id";s:3:"889";s:5:"score";s:18:"11.027892170691759";}i:8;O:8:"stdClass":2:{s:7:"post_id";s:3:"252";s:5:"score";s:17:"9.770674851658331";}i:9;O:8:"stdClass":2:{s:7:"post_id";s:3:"423";s:5:"score";s:17:"9.383932065319893";}i:10;O:8:"stdClass":2:{s:7:"post_id";s:3:"224";s:5:"score";s:17:"8.949695848609034";}i:11;O:8:"stdClass":2:{s:7:"post_id";s:3:"895";s:5:"score";s:16:"8.83066759316686";}}
  _wp_rp_related_posts_query_result_cache_4: a:8:{i:0;O:8:"stdClass":2:{s:7:"post_id";s:3:"166";s:5:"score";s:18:"22.872053889003755";}i:1;O:8:"stdClass":2:{s:7:"post_id";s:3:"142";s:5:"score";s:18:"18.778686887411975";}i:2;O:8:"stdClass":2:{s:7:"post_id";s:2:"78";s:5:"score";s:17:"18.08819439147141";}i:3;O:8:"stdClass":2:{s:7:"post_id";s:3:"246";s:5:"score";s:18:"17.477511755240023";}i:4;O:8:"stdClass":2:{s:7:"post_id";s:4:"1020";s:5:"score";s:16:"16.7778449311753";}i:5;O:8:"stdClass":2:{s:7:"post_id";s:3:"244";s:5:"score";s:18:"15.854271536674663";}i:6;O:8:"stdClass":2:{s:7:"post_id";s:2:"82";s:5:"score";s:17:"15.76536801178127";}i:7;O:8:"stdClass":2:{s:7:"post_id";s:3:"222";s:5:"score";s:17:"15.60227160135727";}}
author:
  login: pat
  email: patmaddox@me.com
  display_name: pat
  first_name: Pat
  last_name: Maddox
excerpt: !ruby/object:Hpricot::Doc
  options: {}
---
<p>We all love when software works perfectly, but things go wrong more often than not. In fact, we use computers largely to help us prevent errors... but only if we build the software with proper error-handling in the first place.</p>
<p>A feature's "happy path" usually leads to straightforward tests and implementation code - we set up the state of the world, run through a few steps, and check the resulting state. But what about the "not so happy path?"</p>
<p>How should the software behave when the user provides bad input? Or when the software can't connect to the database? Or when the network goes down?</p>
<p>We want our software to gracefully handle common error conditions, and to maintain system integrity even in the face of catastrophic failure.</p>
<p>On top of all that, we want our code to make sense.</p>
<p>Most programming languages - including Ruby - provide some sort of an exception-handling mechanism for when things go wrong.</p>
<p>But when should you use exceptions, and when should you go with another approach? What other approaches can you use, anyway?</p>
<p>Try this simple rule of thumb: ask yourself, does this error condition arise in an unlikely, or unwanted situation (aka is it "exceptional")? If so, exceptions will help you out! If not, you might want to represent your failures a different way.</p>
<p>Let's look at a few examples...</p>
<p>A user provides bad input - is that exceptional? Probably not... users provide bad input all the time, sometimes intentionally! You want to validate user input, but invalid input generally doesn't warrant using exceptions.</p>
<p>The software can't connect to the database - is that exceptional? Probably! If the software runs server-side, then the user likely doesn't know anything about the database. The software abstracts the database from the user... and if the software depends on a database, and it can't connect to the database, then that represents an exceptional error and you'll want to use an exception.</p>
<p>Alright, last one: the network goes down. Is that exceptional? Maybe... it happens commonly enough that we can consider it a normal failure condition. However, some software absolutely relies on a network connection to operate. If you can reasonably use a piece of software without a network connection, then a failed network connection probably doesn't warrant an exception. On the other hand, if the software needs a network connection to perform the simplest task, then a missing network connection probably represents an exceptional condition. And if the network connection dies in the middle of a connected operation... that's definitely time for an exception!</p>
<p>Choosing whether you want to use exceptions or not will determine how you write your tests. Treating failures as a normal condition can require a bit more code, but usually makes for a more explicit interface. Using exceptions can feel like the right approach to handling errors, but you'll need to document them well because Ruby has no mechanism for declaring possible exceptions in a chunk of code. If you call some code which raises an exception and you don't handle it, it can take down your entire program.</p>
<p>We'll look at failure conditions, exceptions, and their influence on design and tests in future articles. For now, just remember the simple rule of thumb: if a failure condition arises from a normal interaction with your software, then don't use exceptions. If something goes wrong through no fault of the user, then exceptions can save the day.</p>
